### ISSUE TITLE
Allow translations to be added/removed more easily

### ISSUE THREAD

**Issue by fahhem** [idris/django-quran#4]
Salaam,

I've attached below a patch that enables adding and removing translation files and have it included in the quran_loaddata command to enable easier initial setup.

Edit: Apparently patches don't get added very easily in issues. I don't want to fork for a single patch, so I've just uploaded it here: http://fahhem.com/0001-Allow-translations-to-be-added-removed-easily.patch

**Comment by idris** [comment]
Thanks, I'll add this in the next day or so.

**Comment by idris** [comment]
Commited: 9b7b27068b3e13b290289c62c324af5891108908
